const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const config=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
assert.match(config.home,/[/\\]keivotos-modularization-[^/\\]+[/\\]home$/);
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL});
 const context=await browser.newContext({viewport:{width:1280,height:850}});
 const page=await context.newPage();page.setDefaultTimeout(12000);
 const report={checks:[],errors:[]};
 page.on('pageerror',error=>report.errors.push(error.message));
 await context.tracing.start({screenshots:true,snapshots:true});
 const check=value=>{report.checks.push(value);console.log('PASS: '+value);};
 async function api(url,method='GET',body){return page.evaluate(async({url,method,body})=>{const response=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,data:await response.json()};},{url,method,body});}
 async function waitDisk(name,expected){
  const filename=path.join(config.mediaLocal||config.media,name);
  for(let attempt=0;attempt<30&&fs.readFileSync(filename,'utf8')!==expected;attempt++)await new Promise(resolve=>setTimeout(resolve,100));
  assert.equal(fs.readFileSync(filename,'utf8'),expected);
 }
 try{
  await page.goto(config.url);
  assert.equal((await api('/api/suite/modules/language/enable','POST')).status,200);
  fs.mkdirSync((config.mediaLocal||config.media)+'-other');
  const applied=await api('/api/suite/folders/apply','POST',{folders:[
   {path:config.media,display_name:'Notes',role:'language'},
   {path:config.media+'-other',display_name:'Other notes',role:'language'}
  ]});
  assert.equal(applied.status,200,JSON.stringify(applied));
  const sourceId=applied.data.sources.find(source=>source.display_name==='Notes').source_id;
  const otherSourceId=applied.data.sources.find(source=>source.display_name==='Other notes').source_id;
  await page.getByRole('button',{name:'Open Keivotos menu'}).click();
  await page.locator('.app-drawer').getByRole('button',{name:'Language',exact:true}).click();
  const welcome=page.getByRole('tab',{name:'Welcome.md',exact:true});
  await welcome.click();
  const editor=page.getByRole('textbox',{name:'Edit Welcome.md'});
  await editor.fill('# Updated locally\n');
  await page.waitForTimeout(700);
  assert.equal(fs.readFileSync(path.join(config.mediaLocal||config.media,'Welcome.md'),'utf8'),'# Local note\n');
  const closeWelcome=page.getByRole('button',{name:'Close Welcome.md'});
  assert.equal(await closeWelcome.locator('.dirty-glyph').evaluate(node=>getComputedStyle(node).display),'block');
  await closeWelcome.hover();
  assert.equal(await closeWelcome.locator('.close-glyph').evaluate(node=>getComputedStyle(node).display),'block');
  await closeWelcome.focus();
  assert.equal(await closeWelcome.locator('.close-glyph').evaluate(node=>getComputedStyle(node).display),'block');
  await editor.press('Control+s');
  await waitDisk('Welcome.md','# Updated locally\n');
  await editor.fill('# Temporary edit\n');
  await editor.fill('# Updated locally\n');
  assert.equal(await page.getByRole('button',{name:'Save Welcome.md'}).count(),0);
  assert.equal(await page.evaluate(sourceId=>localStorage.getItem(`keivotos:language-draft:${sourceId}:Welcome.md`),sourceId),null);
  await editor.fill('# Mouse save\n');
  await page.getByRole('button',{name:'Save Welcome.md'}).click();
  await waitDisk('Welcome.md','# Mouse save\n');
  check('Ctrl+S and the visible Save action write only on request; undo to saved text returns clean');

  await editor.fill('# Close and save\n');
  await closeWelcome.click();
  const decision=page.getByRole('dialog',{name:'Unsaved Markdown changes'});
  await page.screenshot({path:path.join(config.output,'language-dirty-dialog.png')});
  await decision.press('Shift+Tab');
  assert.equal(await decision.getByRole('button',{name:'Discard changes'}).evaluate(node=>document.activeElement===node),true);
  await decision.press('Tab');
  assert.equal(await decision.getByRole('button',{name:'Save',exact:true}).evaluate(node=>document.activeElement===node),true);
  await decision.press('Escape');
  await decision.waitFor({state:'detached'});
  assert.equal(await editor.inputValue(),'# Close and save\n');
  await closeWelcome.click();
  await decision.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('tab',{name:'Welcome.md',exact:true}).waitFor({state:'detached'});
  await waitDisk('Welcome.md','# Close and save\n');
  await page.getByRole('combobox',{name:'Open Markdown file'}).selectOption('Welcome.md');
  await page.getByRole('tab',{name:'Welcome.md',exact:true}).waitFor();
  await page.getByRole('textbox',{name:'Edit Welcome.md'}).fill('# Discard this edit\n');
  await closeWelcome.click();
  await decision.getByRole('button',{name:'Discard changes'}).click();
  assert.equal(fs.readFileSync(path.join(config.mediaLocal||config.media,'Welcome.md'),'utf8'),'# Close and save\n');
  await page.getByRole('combobox',{name:'Open Markdown file'}).selectOption('Welcome.md');
  await page.getByRole('tab',{name:'Welcome.md',exact:true}).waitFor();
  assert.equal(await page.getByRole('textbox',{name:'Edit Welcome.md'}).inputValue(),'# Close and save\n');
  check('dirty dot and close control offer Save, Keep editing and Discard without deleting the file');

  await page.getByRole('button',{name:'New Markdown file'}).click();
  const rename=page.getByRole('textbox',{name:'Rename Markdown file'});
  await rename.waitFor();
  assert.equal(await rename.inputValue(),'New File');
  assert.deepEqual(await rename.evaluate(node=>[node.selectionStart,node.selectionEnd]),[0,8]);
  await rename.fill('Study');await rename.press('Enter');
  await page.getByRole('tab',{name:'Study.md'}).waitFor();
  await page.route('**/api/language/document',async route=>{
   if(route.request().method()==='PUT')await new Promise(resolve=>setTimeout(resolve,500));
   await route.continue();
  });
  const studyEditor=page.getByRole('textbox',{name:'Edit Study.md'});
  const firstSave=page.waitForRequest(request=>request.method()==='PUT'&&request.url().includes('/api/language/document'));
  await studyEditor.fill('First draft');
  await page.getByRole('button',{name:'Save Study.md'}).click();
  await firstSave;
  await studyEditor.fill('한국어 notes');
  await page.getByRole('button',{name:'Save Study.md'}).click();
  await page.getByRole('button',{name:'New Markdown file'}).click();
  await rename.press('Escape');
  await waitDisk('Study.md','한국어 notes');
  await page.unroute('**/api/language/document');
  await page.getByRole('button',{name:'New Markdown file'}).click();
  await rename.waitFor();
  assert.equal(await rename.inputValue(),'New File (2)');
  await rename.press('Escape');
  await page.getByRole('tab',{name:'New File (2).md'}).waitFor();
  await page.getByRole('tab',{name:'Study.md'}).click();
  await page.getByRole('textbox',{name:'Edit Study.md'}).fill('Save before rename');
  await page.getByRole('tab',{name:'Study.md'}).dblclick();
  await decision.getByRole('button',{name:'Keep editing'}).click();
  assert.equal(await rename.count(),0);
  await page.getByRole('tab',{name:'Study.md'}).dblclick();
  await decision.getByRole('button',{name:'Save',exact:true}).click();
  await rename.fill('Study 2');await rename.evaluate(node=>node.blur());
  await page.getByRole('tab',{name:'Study 2.md'}).waitFor();
  check('plus creates collision-safe notes; edits during save remain dirty and rename requires a save decision');

  const current=path.join(config.mediaLocal||config.media,'Study 2.md');
  fs.writeFileSync(current,'external content');
  await page.getByRole('textbox',{name:'Edit Study 2.md'}).fill('unsaved local draft');
  await page.getByRole('button',{name:'Save Study 2.md'}).click();
  await page.getByText(/Markdown file changed outside Keivotos/).waitFor();
  assert.equal(fs.readFileSync(current,'utf8'),'external content');
  assert.equal(await page.getByRole('textbox',{name:'Edit Study 2.md'}).inputValue(),'unsaved local draft');
  check('external edit conflict keeps both disk content and the visible local draft');

  await page.screenshot({path:path.join(config.output,'language.png')});
  assert.equal((await api('/api/suite/modules/language/disable','POST')).status,200);
  assert.equal((await api('/api/language/folders')).status,409);
  assert.equal(fs.readFileSync(current,'utf8'),'external content');
  assert.equal(fs.readFileSync(path.join(config.mediaLocal||config.media,'Welcome.md'),'utf8'),'# Close and save\n');
  check('disable blocks Language operations and leaves original Markdown files untouched');

  assert.equal((await api('/api/suite/modules/language/enable','POST')).status,200);
  await page.reload();
  await page.getByRole('button',{name:'Open Keivotos menu'}).click();
  await page.locator('.app-drawer').getByRole('button',{name:'Language',exact:true}).click();
  await page.getByRole('tab',{name:'Welcome.md',exact:true}).click();
  await page.getByRole('textbox',{name:'Edit Welcome.md'}).fill('# Draft across restart\n');
  await page.close({runBeforeUnload:false});
  assert.equal(fs.readFileSync(path.join(config.mediaLocal||config.media,'Welcome.md'),'utf8'),'# Close and save\n');
  const reopened=await context.newPage();
  reopened.on('pageerror',error=>report.errors.push(error.message));
  await reopened.goto(config.url);
  await reopened.getByRole('button',{name:'Open Keivotos menu'}).click();
  await reopened.locator('.app-drawer').getByRole('button',{name:'Language',exact:true}).click();
  await reopened.getByRole('tab',{name:'Welcome.md',exact:true}).click();
  const recovered=reopened.getByRole('textbox',{name:'Edit Welcome.md'});
  assert.equal(await recovered.inputValue(),'# Draft across restart\n');
  assert.equal(await reopened.getByRole('button',{name:'Save Welcome.md'}).count(),1);
  await recovered.press('Control+s');
  await waitDisk('Welcome.md','# Draft across restart\n');
  await reopened.waitForFunction(sourceId=>!localStorage.getItem(`keivotos:language-draft:${sourceId}:Welcome.md`),sourceId);
  check('closing without saving preserves a recoverable draft across a new browser session');

  await recovered.fill('# Folder save A\n');
  await reopened.getByRole('button',{name:'New Markdown file'}).click();
  const newName=reopened.getByRole('textbox',{name:'Rename Markdown file'});
  await newName.fill('Second');await newName.press('Enter');
  await reopened.getByRole('textbox',{name:'Edit Second.md'}).fill('Folder save B');
  await reopened.getByRole('combobox',{name:'Language folder'}).selectOption(otherSourceId);
  const reopenedDecision=reopened.getByRole('dialog',{name:'Unsaved Markdown changes'});
  await reopenedDecision.getByRole('button',{name:'Save',exact:true}).click();
  await waitDisk('Welcome.md','# Folder save A\n');
  await waitDisk('Second.md','Folder save B');
  await reopened.getByRole('combobox',{name:'Language folder'}).selectOption(sourceId);
  await reopened.getByRole('tab',{name:'Welcome.md',exact:true}).click();
  await reopened.getByRole('textbox',{name:'Edit Welcome.md'}).fill('# Module leave draft\n');
  await reopened.getByRole('button',{name:'Open Keivotos menu'}).click();
  const drawer=reopened.locator('.app-drawer');
  await drawer.getByRole('button',{name:'Files',exact:true}).click();
  await reopenedDecision.getByRole('button',{name:'Keep editing'}).click();
  assert.equal(await reopened.getByRole('textbox',{name:'Edit Welcome.md'}).inputValue(),'# Module leave draft\n');
  await drawer.getByRole('button',{name:'Files',exact:true}).click();
  await reopenedDecision.getByRole('button',{name:'Discard changes'}).click();
  await reopened.getByRole('textbox',{name:'Edit Welcome.md'}).waitFor({state:'detached'});
  await waitDisk('Welcome.md','# Folder save A\n');
  await reopened.getByRole('button',{name:'Open Keivotos menu'}).click();
  await reopened.locator('.app-drawer').getByRole('button',{name:'Language',exact:true}).click();
  await reopened.getByRole('tab',{name:'Welcome.md',exact:true}).click();
  assert.equal(await reopened.getByRole('textbox',{name:'Edit Welcome.md'}).inputValue(),'# Folder save A\n');
  check('folder switch saves all dirty tabs; module switch asks before leaving and discard keeps disk bytes');
  assert.deepEqual(report.errors,[]);
 }finally{
  fs.writeFileSync(path.join(config.output,'report.json'),JSON.stringify(report,null,2));
  await context.tracing.stop({path:path.join(config.output,'trace.zip')});await browser.close();
 }
})().catch(error=>{console.error(error);process.exitCode=1;});
