const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const config=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();page.setDefaultTimeout(15000);
 const report={checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
 await context.tracing.start({screenshots:true,snapshots:true});
 const check=x=>{report.checks.push(x);console.log('PASS: '+x);};
 async function api(url,method='GET',body){return page.evaluate(async({url,method,body})=>{const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()};},{url,method,body});}
 async function shot(name){await page.screenshot({path:path.join(config.output,name+'.png')});}
 try{
  await page.goto(config.url);
  assert.equal((await api('/api/manga/library')).status,409);
  assert.equal((await api('/api/suite/modules/manga/enable','POST')).status,200);
  const add=await api('/api/suite/folders/apply','POST',{folders:[{path:config.media,display_name:'Manga',role:'manga'}]});assert.equal(add.status,200,JSON.stringify(add));
  assert.equal((await api('/api/manga/library')).data.total,8);
  await page.getByRole('button',{name:'Open Keivotos menu'}).click();await page.locator('.app-drawer').getByRole('button',{name:'Manga',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.manga-tile img').length===8&&[...document.querySelectorAll('.manga-tile img')].every(i=>i.complete&&i.naturalWidth>0));
  await shot('manga-library');
  await page.getByLabel('Search manga').fill('quiet');await page.waitForTimeout(450);assert.equal(await page.locator('.manga-tile').count(),1);
  await page.getByLabel('Search manga').fill('');await page.waitForTimeout(450);
  check('optional Manga enables, adopts a source, renders eight covers and searches names');
  const tile=page.getByRole('button',{name:'The Quiet Valley',exact:true});await tile.click();
  const dialog=page.getByRole('dialog',{name:'The Quiet Valley chapters'});
  await dialog.getByRole('button',{name:'Chapter 10',exact:true}).waitFor();
  assert.deepEqual(await page.locator('.chapter-list button').allTextContents(),['Chapter 1›','Chapter 2›','Chapter 10›']);
  await shot('manga-chapters');
  await page.mouse.click(20,500);await dialog.waitFor({state:'detached'});assert(await tile.evaluate(n=>n===document.activeElement));
  await tile.click();await dialog.getByRole('button',{name:'Chapter 1',exact:true}).click();
  const reader=page.getByRole('dialog',{name:'Manga reader'});
  await page.getByAltText('Page 2',{exact:true}).waitFor();
  await reader.evaluate(n=>n.scrollTo({top:1000}));
  await page.waitForFunction(()=>document.querySelector('img[alt="Page 2"]')?.naturalWidth>0);
  const box=await reader.boundingBox();assert.equal(box.width,1440);assert.equal(box.height,1000);
  assert((await reader.locator('img').count())<13);
  await shot('manga-reader-fit');
  const back=page.getByRole('button',{name:'Back to chapters'});
  await page.mouse.move(1100,400);await page.waitForTimeout(220);
  const resting=(await back.boundingBox()).width;
  await back.hover();await page.waitForTimeout(70);const middle=(await back.boundingBox()).width;
  await page.waitForTimeout(180);const expanded=(await back.boundingBox()).width;
  assert(middle>resting&&middle<expanded);
  assert.equal(await back.evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(51, 51, 59)');
  await page.mouse.move(1100,400);await page.waitForTimeout(220);assert.equal((await back.boundingBox()).width,resting);
  await page.getByLabel('Reading layout').selectOption('vertical');
  await reader.evaluate(n=>n.scrollTo({top:1500}));await page.waitForTimeout(350);
  assert(await reader.evaluate(n=>n.scrollTop>0));
  const width=await page.locator('.page[data-page="1"]').evaluate(n=>n.getBoundingClientRect().width);assert.equal(width,1000);
  await shot('manga-reader-vertical');
  await page.getByLabel('Reading layout').focus();await page.keyboard.press('Tab');assert(await back.evaluate(n=>n===document.activeElement));
  await back.click();await reader.waitFor({state:'detached'});assert(await dialog.getByRole('button',{name:'Chapter 1',exact:true}).evaluate(n=>n===document.activeElement));
  check('chapter window closes outside; reader fills browser, bounds mounted images, fits/scrolls and animates opaque Back with focus restoration');
  await dialog.getByRole('button',{name:'Chapter 2',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('img[alt="Page 1"]')?.naturalWidth>0);
  await page.keyboard.press('Escape');await reader.waitFor({state:'detached'});
  await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});
  check('CBZ chapter pages decode without extraction and Escape returns through chapters to the library');
  await context.route('**/api/manga/pages?*',route=>route.fulfill({status:422,contentType:'application/json',body:JSON.stringify({detail:'This chapter cannot be opened. See Logs.'})}));
  await tile.click();await dialog.getByRole('button',{name:'Chapter 1',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'See Logs'}).waitFor();await back.click();await page.keyboard.press('Escape');
  await context.unroute('**/api/manga/pages?*');
  check('chapter errors remain concise and preserve the route back to the library');
  assert.equal((await api('/api/suite/modules/manga/disable','POST')).status,200);
  assert.equal((await api('/api/manga/library')).status,409);
  assert((await api('/api/files/sources')).data.some(s=>s.role==='manga'));
  assert.equal((await api('/api/suite/modules/manga/enable','POST')).status,200);
  assert.equal((await api('/api/manga/library')).data.total,8);
  assert.deepEqual(report.errors,[]);
  check('disable rejects Manga work and preserves source registration and rediscovery');
 }finally{fs.writeFileSync(path.join(config.output,'report.json'),JSON.stringify(report,null,2));await context.tracing.stop({path:path.join(config.output,'trace.zip')});await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
